# Generated by Django 4.2.7 on 2026-02-07 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='政策标题')),
                ('content', models.TextField(blank=True, verbose_name='政策内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='policies/', verbose_name='政策文件')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '以旧换新政策',
                'verbose_name_plural': '以旧换新政策',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='RecycleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('category', models.CharField(max_length=50, verbose_name='产品类型')),
                ('brand', models.CharField(max_length=50, verbose_name='产品品牌')),
                ('model', models.CharField(max_length=100, verbose_name='产品型号')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均回收价格')),
                ('scrape_date', models.DateField(verbose_name='爬取日期')),
                ('price_history', models.JSONField(blank=True, default=list, verbose_name='历史价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回收产品',
                'verbose_name_plural': '回收产品',
                'ordering': ['-scrape_date'],
                'indexes': [models.Index(fields=['category', 'brand', 'model'], name='recycle_rec_categor_2ba515_idx'), models.Index(fields=['-scrape_date'], name='recycle_rec_scrape__1c61b2_idx')],
            },
        ),
    ]
